# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0004_auto_20191224_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('progrmmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelApp.Programmer')),
            ],
        ),
    ]
